#!/bin/sh

# Check if the first argument is "-g"
if [ "$1" = "-g" ]; then

    # Get the voltage for core
    TEMP_VALUE=$(/usr/bin/vcgencmd measure_volts core)

    # Extract the numeric value
    TEMP_CLEANED=$(echo $TEMP_VALUE | grep -o '[0-9]\+\.[0-9]\+')

    # Convert to mV and output the result
    TEMP_MV=$(awk -v temp_cleaned=$TEMP_CLEANED "BEGIN {print int(temp_cleaned * 1000)}")

    # Output SNMP OID, type and voltage in mV
    echo .1.3.6.1.4.1.8072.9999.9999.2
    echo gauge
    echo $TEMP_MV
fi

# Exit the script
exit 0
